data:
  root: ./data
  img_size: 224
  batch_size: 128
  num_workers: 2
  val_split: 0.2

phase_test:
  epochs: 3
  lr: 1.0e-3
  freeze_backbone: true
# Paramètres spécifiques aux deux étapes
phase1:
  epochs: 15
  lr: 1.0e-3
  freeze_backbone: true

phase2:
  epochs: 10
  lr: 1.0e-5  # 0.00001
  freeze_backbone: false

output_dir: outputs
